version: "3.9"
services:
  web:
    build: .
    image: "images/simft_akreditasi:latest"  # Anda mungkin ingin mengganti "iamges" menjadi "images"
    restart: always
    container_name: simft_akreditasi
    ports:
      - "80:80"