version: "3.9"
services:
  web:
    build: .
    image: "asai2001/19533119_akreditasi:latest"  # Anda mungkin ingin mengganti "iamges" menjadi "images"
    restart: always
    container_name: 19533119_akreditasi
    ports:
      - "89:80"
    expose:
      - '89'